### PR TITLE
Improve Slack integration

### PR DESCRIPTION
**Pull request by geoffrey-brier**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | yes |
| BC breaks? | yes |
| Deprecations? | no |
| Fixed tickets |  |

Hi!

I have improved the Slack recipe. Basically there are two things here:
- Errors coming from Slack now throw an exception (BC)
- You can use all of the Slack API options

You can do these sort of things:

``` php
set('slack', function () {
    $server = \Deployer\Task\Context::get()->getServer();
    if ($server instanceof \Deployer\Server\Local) {
        $user = env('local_user');
    } else {
        $user = $server->getConfiguration()->getUser() ? : null;
    }

    $revision = trim(runLocally('git log -n 1 --format="%h"'));

    return [
        'unset_text'  => true,
        'token'       => 'xxx',
        'team'        => 'yyy',
        'channel'     => '#zzz',
        'username'    => 'deployer',
        'icon'        => ':shipit:',
        'attachments' => [[
            'text'     => sprintf("Revision %s deployed to %s by %s", substr($revision, 0, 6), env('stages')[0], $user),
            'title'    => 'Deployment Complete',
            'color'    => "#7CD197",
            'fields'   => [
                [
                    'title' => 'User',
                    'value' => $user,
                    'short' => true
                ],
                [
                    'title' => 'Stage',
                    'value' => env('stages')[0],
                    'short' => true
                ],
                [
                    'title' => 'Branch',
                    'value' => env('branch'),
                    'short' => true
                ],
                [
                    'title' => 'Host',
                    'value' => env('server.name'),
                    'short' => true
                ],
            ]
        ]
    ]];
});
```

Which would give you this output:

deployer

### CODE REVIEW

**Comment by peschee** [comment]
This looks nice.

**Comment by elfet** [comment]
Cool. I like it! Merged.

**Comment by elfet** [comment]
@geoffrey-brier please update PR!

**Comment by geoffrey-brier** [comment]
Hey @elfet, not sure about what you really want me to do ?

**Comment by elfet** [comment]
I'd like to see this 

As default in this recipe.

**Comment by geoffrey-brier** [comment]
All right, I understand 👍 
I need to re-dig into the code a bit and I'll make a PR this week ;)

**Pull request closed without merging**
