### PR TITLE
Fix recipe link or remove them

### PR DESCRIPTION
**Pull request by elfet**
Need yo fix links on recipe page, or remove them at all.

### CODE REVIEW

**Comment by johnny-bit** [comment]
If You're removing recipes table, then it would be good to remove mention of recipe table in next section, right?

**Comment by gordalina** [comment]
it would be best to fix the links on the recipes readme parser rather than deleting the recipes table

**Comment by elfet** [comment]
Can anyone do this? :)

**Comment by gordalina** [comment]
I'll do it

**Comment by oanhnn** [comment]
It is updated
I am closing this issue but please feel free to reopen if there is something else you need addressed.

**Pull request closed without merging**
