### PR TITLE
fixed sentry notification recipe to work with latest API changes

### PR DESCRIPTION
**Pull request by Gamesh**
| Q             | A
| ------------- | ---
| Bug fix?      | Yes
| New feature?  | No
| BC breaks?    | Yes
| Deprecations? | No
| Fixed tickets | N/A

API URL and params changed:
https://docs.sentry.io/api/releases/post-organization-releases/

### CODE REVIEW

**Comment by Gamesh** [comment]
after looking into it some more it appears they have two terms now: release and deploy. I think we should add a deploy as well. Basically you create a release and then deploy that release to specific environments, so maybe recipe should do the same

**Comment by antonmedv** [comment]
Can you do a PR for it too?

**Comment by Gamesh** [comment]
@antonmedv i will, do you think it should part of deploy:sentry or make it a separate one? i would probably do it inside the same, first create a release and then a deployment after all for us it's mostly the same

**Comment by antonmedv** [comment]
What's most common way of using it? Will somebody need it as separate recipe? I think if this is no for most of cases - part of deploy:sentry.

**Comment by Gamesh** [comment]
i can't think of any such use case, so let's first implement it as one task, make it work and if somebody complains we can always change it

**Comment by antonmedv** [comment]
Okay, let's do it.

**Pull request merged**
