### PR TITLE
Add comment quietly option to Rollbar recipe.

### PR DESCRIPTION
**Pull request by beeete2**
| Q             | A
| ------------- | ---
| Bug fix?      | No
| New feature?  | No
| BC breaks?    | No
| Deprecations? | No
| Fixed tickets | #154 

I changed the Rollbar recipe.
But I keeping compatibility.

When executed with the setting before change.
- rollbar_username is required parameter
- if comment is not set, default comment is set
```php
set('rollbar_token', 'set your rollbar token');
set('target', 'production');
set('user', 'deployer');
set('branch', 'release');
set('rollbar_username', 'beeete2'); // required parameter
```
The execution result does not change before and after the change.

image1

When executed with the new parameter.
- rollbar_username is optional parameter
- if you do not want to set comments, set `rollbar_quietly` to `true`

```php
set('rollbar_token', 'set your rollbar token');
set('target', 'production');
set('user', 'deployer');
set('branch', 'release');
set('rollbar_quietly', true); // add new parameter. default `false`
// set('rollbar_username', 'beeete2');
```

image2

Of course, if you set a comment, the comment you set will be preferentially set.
```php
set('rollbar_token', 'set your rollbar token');
set('target', 'production');
set('user', 'deployer');
set('branch', 'release');
set('rollbar_comment', 'test comment.');
```

image3

### CODE REVIEW

**Comment by antonmedv** [comment]
Why not just `set('rollbar_comment', '');`?

**Comment by beeete2** [comment]
Because, I think that compatibility will be lost.
I think that I will be surprised when the comment disappears.

**Comment by antonmedv** [comment]
But what's purpose of this pr? What problem do you trying to solve?

**Comment by beeete2** [comment]
I want to solve the following problems.
- rollbar_username to optional param
- not post the comment to rollbar

I want to keep compatibility.
But, Is the default comment completely unnecessary?

**Comment by antonmedv** [comment]
No, default comment can be tripped. And yes -  keep compatibility.

**Pull request closed without merging**
