### PR TITLE
Update telegram.php

### PR DESCRIPTION
**Pull request by razseo**
Added documentation

| Q             | A
| ------------- | ---
| Bug fix?      | No
| New feature?  | No
| BC breaks?    | No
| Deprecations? | No
| Fixed tickets | N/A

> Do not forget to add notes about your changes to [CHANGELOG.md](https://github.com/deployphp/recipes/blob/master/CHANGELOG.md)

### CODE REVIEW

**Comment by antonmedv** [comment]
Please, add docs in `docs` folder.

**Comment by antonmedv** [comment]
ping @razseo

**Comment by razseo** [comment]
https://github.com/deployphp/recipes/blob/master/docs/telegram.md
Pong? @antonmedv

**Comment by antonmedv** [comment]
Sorry) I was wrong.

**Pull request merged**
