### PR TITLE
$php_errormsg is not global

### PR DESCRIPTION
**Pull request by glensc**
see the manual: http://php.net/manual/en/reserved.variables.phperrormsg.php

### CODE REVIEW

**Comment by elfet** [comment]
>While $php_errormsg is a global, it is not a superglobal.

You'll have to qualify it with a global keyword inside a function.

<?php
function checkErrormsg()
{
    global $php_errormsg;
    @strpos();
    return $php_errormsg;
}
?>

**Comment by elfet** [comment]
Is it possible to avoid it usage at all?

**Comment by glensc** [comment]
please read the docs. it is not global. you must not `global` it.

**Comment by elfet** [comment]
Ad if it's appears in inner scope?

**Comment by glensc** [comment]
inner scope of what? point to code lines perhaps?

**Comment by antonmedv** [comment]
Fixed.

**Comment by glensc** [comment]
what exactly is fixed? link to commit?

search for $php_errormsg still yields a match:
https://github.com/deployphp/recipes/search?utf8=%E2%9C%93&q=%24php_errormsg&type=
https://github.com/deployphp/recipes/blob/15d28973b35d8a1f92e466791cd111bdce058a88/recipe/sentry.php#L12

**Comment by antonmedv** [comment]
Yeap. Missed this one.

**Pull request closed without merging**
