### PR TITLE
[slack] bring back stage and remove var_dump

### PR DESCRIPTION
**Pull request by snowiow**
| Q             | A
| ------------- | ---
| Bug fix?      | Yes
| New feature?  | No
| BC breaks?    | No
| Deprecations? | No
| Fixed tickets | N/A

Is stage still an array? Otherwise I'll change that. But currently it's just an empty string, which is printed in the slack message.

### CODE REVIEW

**Comment by antonmedv** [comment]
There is no stages in 5.x

**Comment by snowiow** [comment]
but then the stage part of the the Slack message should be removed completely and there is still a var_dump in the code

**Comment by antonmedv** [comment]
Yes, try. Now I'm in process of rewriting slack recipe myself.

**Comment by snowiow** [comment]
Ok, the PR is here https://github.com/deployphp/recipes/pull/140

**Pull request closed without merging**
