### PR TITLE
prevent rsync without $dst set

### PR DESCRIPTION
**Pull request by torvitas**
if $dst is not set here we are going to sync to root and even worse - depending on rsync flags and permission - might end up deleting everything we have write permission to

### CODE REVIEW

**Comment by johnny-bit** [comment]
Is it really that much kaboom inducing? By default rsync defaults to release path, which should be present... but hey, i guess it's good to have such check. maybe add also check for non-empty source?

**Comment by torvitas** [comment]
Sadly it already induced kaboom. The last deployment just wiped clean a customer's server.

**Comment by johnny-bit** [comment]
Nice... You know, I usually don't even configure dst and nothing bad comes
out of it, usually because it reads release path and if it cannot - it
bails out early. COnsidering that release_path might be properly enginered
link that point to root instead of proper path and wipes whole system
clean... Yeah this might be good idea to prevent problematic dst from
inducing kabooms.

In the mean time: src checking would be good idea too would You like to
ammend Your pr with check for src too?

2016-01-05 13:05 GMT+01:00 Sascha Marcel Schmidt <notifications@github.com>:

> Sadly it already induced kaboom. The last deployment just wiped clean a
> customer's server.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/deployphp/recipes/pull/38#issuecomment-168982668>.
>



-- 
Pozdrawiam,
Hubert Kowalski

**Comment by torvitas** [comment]
I already did that: https://github.com/deployphp/recipes/pull/38/commits

**Comment by johnny-bit** [comment]
Sorry, haven't seen that :wink: IMO looks good.

**Comment by oanhnn** [comment]
Thank you!

**Pull request merged**
