### PR TITLE
Make Phinx Recipes works with Deployer 4

### PR DESCRIPTION
**Pull request by security-database**
- Add Namespace Deployer
- Change Doc
- Rewrite Tasks
- Issue #74

### CODE REVIEW

**Comment by ket4yii** [comment]
Thank you for this PR, but I think it's unnecessary to rewrite a lot of code(and delete some configuration checks). A problem with it, as far as I can see, with closures in get/set functions. I think, moving closures like "phinx_get_allowed_config" into upper scope and run it without get (e.g. Deployer\Phinx\phinx_get_allowed_config) could fix it. I'm gonna test it in the near future. Anyway, a lot of thanks for your reply:smile:.

**Comment by security-database** [comment]
hello @ket4yii 
I know, but unable to let it work without rewriting ... :'( Perhaps my skills are not as good as i would like. Always error with closure.

But this code works ;) Also, i've include $allowedOptions into phinx_get_allowed_config instead of putting $allowedOptions into all tasks.

Thanks to your help ;)
Thanks to you

**Comment by ket4yii** [comment]
> putting $allowedOptions into all tasks

But they are different for some tasks and this is the reason why it was written that way(closure that get $allowedOptions and returns built command).

**Comment by security-database** [comment]
Sorry about that, i haven't read properly $allowedOptions difference between task. Seed have is own. My code could break some things.

**Comment by ket4yii** [comment]
@security-database I've made some [changes in the recipe](https://github.com/ket4yii/recipes/tree/bugfix/phinx-compat-v4), could you test it and if you have some suggestions about the code or find a bug, make a PR?

**Comment by security-database** [comment]
Your code work very well and better than mine ;) Sooo simple .... You can push it ;)

**Comment by elfet** [comment]
@security-database @ket4yii please, make PR to merge :)

**Comment by ket4yii** [comment]
[It's done](https://github.com/deployphp/recipes/pull/79). I added you in contributors. You can close an #74 and this PR.

**Pull request closed without merging**
