### PR TITLE
use try...catch

### PR DESCRIPTION
**Pull request by vkrms**
| Q             | A
| ------------- | ---
| Bug fix?      | Yes
| New feature?  | No
| BC breaks?    | No
| Deprecations? | No
| Fixed tickets | N/A

> Do not forget to add notes about your changes to [CHANGELOG.md](https://github.com/deployphp/recipes/blob/master/CHANGELOG.md)

***
@antonmedv @petermein @Gamesh
I've encountered an error:  
`fatal: Invalid revision range <hash>..HEAD`  
which prevented the deploy process from finishing. So I had to wrap the git command in try...catch. Probably not the best way to go about that, but I had to do it locally to deploy my project.

### CODE REVIEW

**Comment by Gamesh** [comment]
@vkrms cool thanks for the fix, was it the first ever deploy?
just a note sentry notify should be run after everything else, so the deployment process should go through just it won't notify sentry about it on fail

**Comment by vkrms** [comment]
@Gamesh nope it was about 40th, the error happened (still happens actually) once after every new commit.  The recipe is run after everything, just like in the docs `after('deploy', 'deploy:sentry');`

**Comment by Gamesh** [comment]
interesting. @vkrms have you tried printing out the revision it tries to get the range for? and why it's acting like that?

**Comment by vkrms** [comment]
@Gamesh `git log -1` in the latest release folder returns only the latest commit, so it seems that the range is always invalid cause technically there's no range

**Comment by Gamesh** [comment]
@vkrms if you're referring to `git log -n 1 --format="%h"` on line 144 it's only used to fetch the latest commit to use it as a version number of current release. It's not used in range calculation

**Comment by vkrms** [comment]
@Gamesh no I mean `git log -1` I'm doing on the production server through ssh to figure out what the hell is going on ) I got a feeling it might be connected though I'm not sure

**Pull request merged**
