### PR TITLE
Move the actual request into its own class/method

### PR DESCRIPTION
**Pull request by Xethron**
This is a fix for #150, to make it easier to create your own tasks

| Q             | A
| ------------- | ---
| Bug fix?      | No
| New feature?  | Yes
| BC breaks?    | No
| Deprecations? | No
| Fixed tickets | #150 

> Do not forget to add notes about your changes to [CHANGELOG.md](https://github.com/deployphp/recipes/blob/master/CHANGELOG.md)

Will add changes to docs/changelog once discussed

### CODE REVIEW

**Comment by antonmedv** [comment]
Hi, what purpose of this?

**Comment by Xethron** [comment]
Hello @antonmedv. We discussed this in #150 to make it easier to create your own tasks / messages.

You recommended a static function in a class. Or did I not understand correctly?

**Comment by antonmedv** [comment]
Yes, but lets think of autoloading first and what about other recipes? 
Also, please, can you tell me again why do you need it?

**Comment by Xethron** [comment]
Most of the reasons to why we need it was discussed in #150, but to summerise, the above change will allow me to change this code:

```
task('hipchat:prepare', function() {
    set('hipchat_color', 'yellow');
    set('hipchat_message', 'STARTING: {{user}} started deploying {{application}} from {{branch}} to {{target}}');
});
before('deploy:prepare', 'hipchat:prepare');
after('hipchat:prepare', 'hipchat:notify');

task('hipchat:success', function() {
    set('hipchat_color', 'green');
    set('hipchat_message', 'SUCCESS: {{user}} successfully deployed {{application}} from {{branch}} to {{target}}');
});
after('success', 'hipchat:success');
after('hipchat:success', 'hipchat:notify');

task('hipchat:fail', function() {
    set('hipchat_color', 'red');
    set('hipchat_message', 'FAILED: {{user}} failed to deploy {{application}} from {{branch}} to {{target}}');
});
after('deploy:failed', 'hipchat:fail');
after('hipchat:fail', 'hipchat:notify');

task('hipchat:rolling-back', function() {
    set('hipchat_color', 'red');
    set('hipchat_message', 'ROLLING BACK: {{user}} is rolling back {{application}} on {{target}}');
});
before('rollback', 'hipchat:rolling-back');
after('hipchat:rolling-back', 'hipchat:notify');

task('hipchat:rolled-back', function() {
    set('hipchat_color', 'purple');
    set('hipchat_message', 'ROLLED BACK: {{user}} successfully rolled back {{application}} on {{target}}');
});
after('rollback', 'hipchat:rolled-back');
after('hipchat:rolled-back', 'hipchat:notify');
```
into this
```
task('hipchat:prepare', function() {
    Hipchat::notify('STARTING: {{user}} started deploying {{application}} from {{branch}} to {{target}}', 'yellow');
});
task('hipchat:success', function() {
    Hipchat::notify('SUCCESS: {{user}} successfully deployed {{application}} from {{branch}} to {{target}}', 'green');
});
task('hipchat:fail', function() {
    Hipchat::notify('FAILED: {{user}} failed to deploy {{application}} from {{branch}} to {{target}}', 'red');
});
task('hipchat:rolling-back', function() {
    Hipchat::notify('ROLLING BACK: {{user}} is rolling back {{application}} on {{target}}', 'red');
});
task('hipchat:rolled-back', function() {
    Hipchat::notify('ROLLED BACK: {{user}} successfully rolled back {{application}} on {{target}}', 'purple');
});
before('deploy:prepare', 'hipchat:prepare');
after('success', 'hipchat:success');
after('deploy:failed', 'hipchat:fail');
before('rollback', 'hipchat:rolling-back');
after('rollback', 'hipchat:rolled-back');
```

Which is much smaller / clearer / easier.

**Comment by antonmedv** [comment]
Yes, it's much better. But I can't accept this PR because of a few reasons: 
* Only hipchat implementation. What about others?
* Strange notify interface. Maybe better so standardize it among others.
* What not just implement it as custom recipe for deployer? Like `xethron/deployer-hipchat` package?

**Comment by Xethron** [comment]
How would you recommend we proceed?

**Comment by Xethron** [comment]
This doesn't change the way it has been used in the past at all. So there are no BC breaks. This also works the same as all the others. It just opens up another way to use it. Instead of using the task, you can use the function directly.
This also makes it easier to add other tasks to the Hipchat recipe

**Comment by Xethron** [comment]
Slack also already has tasks for Deploy, Success, and Failure, which Hipchat doesn't have. Which is what I'd like to add to my next commit. Adding this into its own function will make that easier, instead of duplicating code for every task.

**Comment by antonmedv** [comment]
> So there are no BC breaks. This also works the same as all the others. It just opens up another way to use it. 

Yes, there is no BC, you are right. But "_It just opens up another way to use it_" my main concern. 

Now standard recipe recipe offers you one way of doing it. That's is good feature as you migrate from one project to another, pattern always the same. If you need some extra functionality, it's simple to extend it, it's just php anyway. But when new API are introduced, new endpoints are opened there is more stuff to support, and more stuff to break by new BC, lack of docs, difference in implementation — all that stuff kills developer experience. Don't be afraid of creating new packages to extend Deployer (what's why deployer build on top of DI, extendable), maybe they become popular and be signal to refactor and improve core recipes.

**Pull request closed without merging**
