### PR TITLE
add support for place holders in slack messages

### PR DESCRIPTION
**Pull request by kbsali**
I wanted to customize the message sent to slack, but found it hard to find the available variables. Also it wasn't clear to me how to add the name of the user deploying... so here is my proposal (more place holders should/could be added - like the tag name when available for instance - but those serve my needs for now).

### CODE REVIEW

**Comment by gordalina** [comment]
Actually the configuration should be under `get('slack')`

**Comment by kbsali** [comment]
@oanhnn done, thanks for the tip!
@gordalina not sure i get you...

**Comment by kbsali** [comment]
@gordalina : ok, got it! :)

**Comment by kbsali** [comment]
@gordalina : could you tag the latest commit by @oanhnn please?

**Comment by gordalina** [comment]
tagged

**Pull request merged**
