### PR TITLE
Remove completelly unneded outputing of git version

### PR DESCRIPTION
**Pull request by johnny-bit**
I've seen changes @oanhnn made. I was intigued by output being written and I've noticed that echo wound up there unnecessary. Output isn't present in git_cache in common.php that was based on this, so I guess I forgot to make change @elfet requested there present here too.

### CODE REVIEW

**Comment by gordalina** [comment]
ping @johnny-bit

**Comment by johnny-bit** [comment]
Yes?

**Comment by gordalina** [comment]
sorry, i didn't see it was you. lol

**Comment by johnny-bit** [comment]
LOL, ok. Thanks for merging :)

**Comment by gordalina** [comment]
tagged as `3.0.5`

**Pull request merged**
