### PR TITLE
Refactored and added support for icon_url

### PR DESCRIPTION
**Pull request by mvdstam**
This replaces #14

### CODE REVIEW

**Comment by ZeeCoder** [comment]
Final one?

**Comment by mvdstam** [comment]
This is the right one :smile:

**Comment by ZeeCoder** [comment]
Excellent :+1:

**Comment by mvdstam** [comment]
Thanks for the quick response @ZeeCoder! And sorry for the earlier PR; I'm afraid it was a bit early for me this morning. :smile:

**Comment by mvdstam** [comment]
Could you tag the commit by the way? :smile:

**Comment by ZeeCoder** [comment]
[done](https://github.com/deployphp/recipes/releases/tag/3.0.2) :)

**Pull request merged**
